### ISSUE TITLE
你好大佬你的这个背景图我可以整走吗?

### ISSUE THREAD

**Issue by CollinsWalker** [Jackie1123/aNavigation#1]
你好大佬你的这个背景图我可以整走吗?

**Comment by wuhan0823** [comment]
你好，请问一下 怎么换背景

**Comment by HoYuenhang** [comment]
> 你好大佬你的这个背景图我可以整走吗?

可以

**Comment by HoYuenhang** [comment]
> 你好，请问一下 怎么换背景

在style.css里面注释媒体查询下面可以更换小屏幕和大屏幕壁纸

**Comment by wuhan0823** [comment]
好的，谢谢开发者。这里我提一个建议，就是搜索框搜索一个内容能不能跳到新开的一页，不要直接覆盖了了导航网址




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jackie1123"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 中午12:06
收件人: "Jackie1123/aNavigation"<aNavigation@noreply.github.com&gt;; 
抄送: "易清涵"<1963690335@QQ.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Jackie1123/aNavigation] 你好大佬你的这个背景图我可以整走吗? (#1)





  
你好，请问一下 怎么换背景
  
在style.css里面注释媒体查询下面可以更换小屏幕和大屏幕壁纸

**Comment by illidanplus** [comment]
能不能同步到gitee，出国不易。

**Comment by HoYuenhang** [comment]
> 能不能同步到gitee，出国不易。

gitee地址：[https://gitee.com/Yuenhangho/aNavigation](https://gitee.com/Yuenhangho/aNavigation)
