### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by FmgX** [Jackie1123/aNavigation#6]
我在chrome的检查功能下看代码时在书签下<ul>和</ul>之间有东西可用dw，记事本github打开index文件时<ul>和</ul>之间空无一物
![2021-6-21 16-45-15](https://user-images.githubusercontent.com/47731175/122735186-60cca200-d2b1-11eb-924c-efca1a326bb1.png)

![2021-6-21 16-45-51](https://user-images.githubusercontent.com/47731175/122734882-11867180-d2b1-11eb-8134-5a198cc9d618.png)
)
这是两张图

我想知道我怎么样可以修改书签内容。  谢谢大佬

**Comment by FmgX** [comment]
谢谢大佬

**Comment by HoYuenhang** [comment]
书签的修改在 js/main.js 文件里，有“添加书签”注释的地方
