### ISSUE TITLE
请问怎么修改背景图片

### ISSUE THREAD

**Issue by miaowmint** [Jackie1123/aNavigation#7]
RT，导航的背景图片是固定的，请问怎么在代码里修改呢

**Comment by HoYuenhang** [comment]
在css/style.css文件中，找到两个 #main，分别为小屏样式与大屏样式，修改background属性的路径即可

**Comment by miaowmint** [comment]
> 在css/style.css文件中，找到两个 #main，分别为小屏样式与大屏样式，修改background属性的路径即可

js/main.js 318行
// 显示/关闭壁纸
var width = $(document).width();
$('#bg').click(function() {
width < 768 ? ($('#main').css('background-image') == 'none' ? ($('#main').css('background-image', 'url(img/bg-xs.jpg)')) : ($('#main').css('background-image', 'none'))) : $('#main').css('background-image') == 'none' ? ($('#main').css('background-image', 'url(img/bg.jpg)')) : ($('#main').css('background-image', 'none'));
var background = $('#main').css('background-image');
storage.bg = [background];
})

那请问这段代码不用修改是吗

**Comment by HoYuenhang** [comment]
如果你的图片文件名和存放的路径和我原来的一致，什么都不用改直接覆盖掉我原本的图片即可

**Comment by miaowmint** [comment]
> 如果你的图片文件名和存放的路径和我原来的一致，什么都不用改直接覆盖掉我原本的图片即可

我想用的是图片api的图
