### ISSUE TITLE
大佬你好，请问壁纸怎么修改？

### ISSUE THREAD

**Issue by leomanxin** [Jackie1123/aNavigation#8]
我已经替换了img里面的bg.jpg和bg.svg，但还是没用

**Comment by HoYuenhang** [comment]
手机端的壁纸和大屏的壁纸是不一样的。手机端壁纸是在/img/bg-xs.jpg，大屏的壁纸是在/img/bg.jpg

**Comment by leomanxin** [comment]
/img/bg.jpg，大屏下已经替换，但是显示的还是默认的壁纸
<img width="377" alt="屏幕截图 2022-03-10 154145" src="https://user-images.githubusercontent.com/100075596/157612756-9926af86-c757-4e01-9d25-3e8a6546deaa.png">

**Comment by leomanxin** [comment]
> 手机端的壁纸和大屏的壁纸是不一样的。手机端壁纸是在/img/bg-xs.jpg，大屏的壁纸是在/img/bg.jpg
<img width="377" alt="屏幕截图 2022-03-10 154145" src="https://user-images.githubusercontent.com/100075596/157613339-2974f80e-ad64-4565-8286-2c600df8b174.png">

大屏下已经替换，但是还是显示默认壁纸

**Comment by HoYuenhang** [comment]
试一下清除缓存

**Comment by leomanxin** [comment]
谢谢，是缓存的原因
