### ISSUE TITLE
请问大佬怎么可以让搜索框里不弹出搜索历史？

### ISSUE THREAD

**Issue by leomanxin** [Jackie1123/aNavigation#9]
请教大佬，怎么可以让搜索框里不弹出搜索历史。
![屏幕截图 2022-03-13 111132](https://user-images.githubusercontent.com/100075596/158043348-6cc8f9b8-0f86-47af-8a16-5abad881d5f0.png)

**Comment by HoYuenhang** [comment]
这个搜索历史应该是你浏览器的，这个项目没有记录历史的。

**Comment by leomanxin** [comment]
好的，谢谢
